Repository Quansight/ragna, pull requests merged in 2023-11, with the labels that each got.

#147 clarify demo assistant message
  ragna/assistants/_demo.py
Labels: area: user-experience 🙋🏻‍♀️

#146 fix Ragna 101
  docs/tutorials/python-api.md
Labels: area: documentation 📖

#149 Make API / UI origins configurable
  ragna/_api/core.py
  ragna/_cli/config.py
  ragna/_ui/app.py
  ragna/_utils.py
  ragna/core/_config.py
Labels: area: panel-app 💻, area: rest-api 💻

#159 add prominent note about LLM access and instructions on how to get keys
  docs/index.md
  docs/references/faq.md
Labels: area: documentation 📖

#154 Update README.md
  README.md
Labels: type: maintenance 🛠️

#151 Add testing for docs
  docs/how-tos/set-configuration.md
  docs/tutorials/python-api.md
  docs/tutorials/rest-api.md
  environment-dev.yml
  tests/test_docs.py
Labels: area: documentation 📖, type: enhancement 💅

#157 add print for demo auth
  ragna/core/_authentication.py
Labels: area: user-experience 🙋🏻‍♀️

#163 add release notes for v0.1.1
  docs/references/changelog.md
Labels: type: release 🏷️

#164 Add announcement banner with link to blog
  docs/assets/stylesheet.css
  docs/overrides/main.html
  docs/references/changelog.md
  mkdocs.yml
Labels: area: documentation 📖, pr-status: needs review 👀

#187 fix note in Ragna 101
  docs/tutorials/python-api.md
Labels: area: documentation 📖

#170 special case LocalDocument more
  ragna/core/_document.py
  ragna/core/_rag.py
  tests/core/test_e2e.py
  tests/core/test_rag.py
  tests/source_storages/test_source_storages.py
Labels: area: python-api ⌨️

#196 docs: various improvements to Python API tutorial
  docs/tutorials/python-api.md
Labels: area: documentation 📖, type: maintenance 🛠️, pr-status: changes requested 🧱

#198 docs: improvements to REST API tutorial
  docs/tutorials/rest-api.md
Labels: area: documentation 📖, type: maintenance 🛠️, pr-status: changes requested 🧱

#220 fix chat info
  ragna/deploy/_ui/central_view.py
Labels: area: web-ui 💻
