Repository Quansight/ragna, pull requests merged in 2023-10, with the labels that each got.

#91 Update README.md
  README.md
  docs/brand-assets/Ragna-logo-lockup-vertical.png
Labels: type: maintenance 🛠️, pr-status: needs review 👀

#93 use mkdocs-gen-files over custom hooks
  docs/.gitignore
  docs/hooks/cli.py
  docs/hooks/rest_api.py
  environment.yml
  mkdocs.yml
  scripts/docs_gen_files.py
Labels: area: documentation 📖, area: developer-experience 🧑‍💻

#96 ReadTheDocs configuration
  .github/actions/setup-env/action.yml
  .github/workflows/test.yml
  .readthedocs.yml
  environment-dev.yml
Labels: area: documentation 📖, type: maintenance 🛠️

#97 Fix .readthedocs.yml to use conda
  .readthedocs.yml
Labels: type: bug 🐛, area: documentation 📖, pr-status: in-progress 🏗️

#98 try use dynamic path for openapi.json file in docs
  docs/references/rest-api.md
  mkdocs.yml
Labels: area: documentation 📖

#94 Add mypy as static type checker
  .github/workflows/lint.yml
  environment-dev.yml
  pyproject.toml
  ragna/_api/core.py
  ragna/_api/database.py
  ragna/_api/orm.py
  ragna/_api/schemas.py
  ragna/_cli/config.py
  ragna/_cli/core.py
  ragna/_compat.py
  ragna/_utils.py
  ragna/assistants/_api.py
  ragna/assistants/_demo.py
  ragna/assistants/_openai.py
  ragna/core/_components.py
  ragna/core/_config.py
  ragna/core/_document.py
  ragna/core/_queue.py
  ragna/core/_rag.py
  ragna/core/_utils.py
  ragna/source_storages/_chroma.py
  ragna/source_storages/_demo.py
  ragna/source_storages/_lancedb.py
  ragna/utils/__init__.py
  ragna/utils/_misc.py
Labels: area: developer-experience 🧑‍💻, pr-status: needs review 👀

#101 use prettier as markdown / yaml / toml formatter
  .github/actions/setup-env/action.yml
  .pre-commit-config.yaml
  .prettierrc.yaml
  README.md
  docs/community/contribute.md
  docs/get-started.md
  docs/index.md
  environment-dev.yml
Labels: area: developer-experience 🧑‍💻

#102 Add security policy
  SECURITY.md
Labels: pr-status: merge ready 💪

#100 Add initial narrative docs
  README.md
  docs/assets/brand/logo-lockup-horizontal/logo-lockup-horizontal.png
  docs/assets/brand/logo-lockup-horizontal/logo-lockup-horizontal.svg
  docs/assets/brand/logo-lockup-vertical/logo-lockup-vertical-white.png
  docs/assets/brand/logo-lockup-vertical/logo-lockup-vertical-white.svg
  docs/assets/brand/logo-lockup-vertical/logo-lockup-vertical.png
  docs/assets/brand/logo-lockup-vertical/logo-lockup-vertical.svg
  docs/assets/brand/logo-symbol/logo-symbol-white.png
  docs/assets/brand/logo-symbol/logo-symbol-white.svg
  docs/assets/brand/logo-symbol/logo-symbol.png
  docs/assets/brand/logo-symbol/logo-symbol.svg
  docs/assets/stylesheet.css
  docs/community/brand.md
  docs/community/contribute.md
  docs/community/welcome.md
  docs/explanations/understand-rag.md
  docs/get-started.md
  docs/how-tos/images/ragna-config-wizard.png
  docs/how-tos/set-configuration.md
  docs/index.md
  docs/install.md
  docs/references/changelog.md
  docs/references/faq.md
  docs/tutorials/python-api.md
  docs/tutorials/rest-api.md
  docs/tutorials/web-app.md
  mkdocs.yml
Labels: area: documentation 📖

#111 cleanup usort
  pyproject.toml
  ragna/_utils.py
  ragna/assistants/__init__.py
  ragna/core/__init__.py
  ragna/source_storages/__init__.py
  ragna/utils/__init__.py
Labels: type: maintenance 🛠️

#103 Add issue+pr templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area: community 🌱, pr-status: needs review 👀

#113 move public utils into vector db base class
  ragna/__init__.py
  ragna/source_storages/_chroma.py
  ragna/source_storages/_lancedb.py
  ragna/source_storages/_vector_database.py
  ragna/utils/__init__.py
  ragna/utils/_chunk.py
  ragna/utils/_misc.py
  tests/test_utils.py
Labels: type: maintenance 🛠️

#114 Fix blank issues display in template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: bug 🐛

#117 increase test timeout
  tests/api/test_e2e.py
  tests/utils.py
Labels: area: developer-experience 🧑‍💻, area: testing ✅

#115 fail doc build on warnings in CI
  .readthedocs.yml
  mkdocs.yml
  scripts/docs/gen_files.py
  scripts/docs/rtd.py
Labels: area: developer-experience 🧑‍💻

#61 Add UI
  .pre-commit-config.yaml
  docs/assets/stylesheet.css
  pyproject.toml
  ragna/_api/core.py
  ragna/_cli/core.py
  ragna/_ui/__init__.py
  ragna/_ui/api_wrapper.py
  ragna/_ui/app.py
  ragna/_ui/auth_page.py
  ragna/_ui/central_view.py
  ragna/_ui/components/file_uploader.py
  ragna/_ui/imgs/chat_bubble.svg
  ragna/_ui/imgs/cloud-upload.svg
  ragna/_ui/imgs/ragna_logo.svg
  ragna/_ui/js.py
  ragna/_ui/left_sidebar.py
  ragna/_ui/main_page.py
  ragna/_ui/modal_configuration.py
  ragna/_ui/modal_welcome.py
  ragna/_ui/resources/upload.js
  ragna/_ui/right_sidebar.py
  ragna/_ui/styles.py
  ragna/_utils.py
  ragna/assistants/_api.py
Labels: pr-status: in-progress 🏗️, area: panel-app 💻

#118 Add minimal REST API tutorial
  docs/explanations/what-is-rag.md
  docs/tutorials/python-api.md
  docs/tutorials/rest-api.md
  docs/tutorials/web-app.md
  mkdocs.yml
Labels: pr-status: in-progress 🏗️

#119 docs cleanup
  .github/ISSUE_TEMPLATE/config.yml
  docs/install.md
Labels: area: documentation 📖

#133 fix chat param unpacking
  pyproject.toml
  ragna/core/_document.py
  ragna/core/_rag.py
  ragna/core/_utils.py
  tests/core/test_rag.py
Labels: type: bug 🐛
