Repository Quansight/ragna, pull requests merged in 2024-02, with the labels that each got.

#309 move BC policy into documentation
  SECURITY.md
  docs/install.md
  docs/references/release-notes.md
  mkdocs.yml
Labels: area: documentation 📖

#308 remove invalid font CSS declaration
  ragna/deploy/_ui/app.py
Labels: area: web-ui 💻

#314 fix invalid escape warning when building docs
  ragna/deploy/_cli/config.py
Labels: area: documentation 📖, area: developer-experience 🧑‍💻

#316 re-add Authentication documentation
  docs/references/python-api.md
  ragna/deploy/__init__.py
Labels: area: documentation 📖

#315 Set up git-lfs and track relevant files
  .gitattributes
  .readthedocs.yml
  docs/community/contribute.md
  docs/how-tos/images/ragna-config-wizard.png
  environment-dev.yml
Labels: type: maintenance 🛠️, pr-status: needs review 👀

#324 use truly-sane-lists plugin
  environment-dev.yml
  mkdocs.yml
Labels: area: documentation 📖, type: maintenance 🛠️, pr-status: changes requested 🧱

#322 use FastAPI test client for testing
  scripts/add_chats.py
  tests/deploy/api/test_e2e.py
  tests/utils.py
Labels: type: maintenance 🛠️, area: testing ✅

#321 update outdated actions
  .github/actions/setup-env/action.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
Labels: type: maintenance 🛠️

#320 remove memory option for state db
  ragna/__init__.py
  ragna/deploy/_api/core.py
  ragna/deploy/_cli/config.py
  ragna/deploy/_config.py
Labels: area: rest-api 💻

#317 only send sources on first chunk when streaming
  ragna/_compat.py
  ragna/deploy/_api/core.py
Labels: area: rest-api 💻

#318 refactor config docs
  docs/how-tos/images/ragna-config-wizard.png
  docs/how-tos/set-configuration.md
  docs/references/config.md
  docs/tutorials/python-api.md
  docs/tutorials/rest-api.md
  mkdocs.yml
  ragna/deploy/_config.py
  scripts/docs/gen_files.py
Labels: area: documentation 📖

#319 restrict accepted files in file uploader
  ragna/deploy/_ui/components/file_uploader.py
  ragna/deploy/_ui/modal_configuration.py
Labels: area: web-ui 💻
