Repository Quansight/ragna, pull requests merged in 2024-04, with the labels that each got.

#390 fix mypy after pydantic 2.7
  ragna/deploy/_cli/config.py
Labels: type: maintenance 🛠️

#393 use relative links for all images in UI
  ragna/deploy/_ui/components/file_uploader.py
  ragna/deploy/_ui/left_sidebar.py
Labels: area: web-ui 💻

#387 Remove Mosaic Assistant
  docs/references/faq.md
  docs/tutorials/gallery_python_api.py
  ragna/assistants/__init__.py
  ragna/assistants/_mosaicml.py
Labels: type: maintenance 🛠️, pr-status: needs review 👀, pr-status: merge ready 💪

#398 bump mypy to 1.10
  environment-dev.yml
  ragna/assistants/_api.py
Labels: type: maintenance 🛠️
