Repository Quansight/ragna, pull requests merged in 2024-05, with the labels that each got.

#402 mypy for sqlalchemy
  pyproject.toml
  ragna/deploy/_api/database.py
  ragna/deploy/_api/orm.py
Labels: type: maintenance 🛠️, area: developer-experience 🧑‍💻

#412 update ignored deprecation warnings
  pyproject.toml
Labels: type: maintenance 🛠️

#312 CSS refactor
  pyproject.toml
  ragna/deploy/_ui/app.py
  ragna/deploy/_ui/auth_page.py
  ragna/deploy/_ui/central_view.py
  ragna/deploy/_ui/css/auth/button.css
  ragna/deploy/_ui/css/auth/column.css
  ragna/deploy/_ui/css/auth/html.css
  ragna/deploy/_ui/css/auth/textinput.css
  ragna/deploy/_ui/css/central_view/column.css
  ragna/deploy/_ui/css/central_view/html.css
  ragna/deploy/_ui/css/central_view/row.css
  ragna/deploy/_ui/css/chat_info/button.css
  ragna/deploy/_ui/css/chat_info/markdown.css
  ragna/deploy/_ui/css/chat_interface/button.css
  ragna/deploy/_ui/css/chat_interface/card.css
  ragna/deploy/_ui/css/chat_interface/chatmessage.css
  ragna/deploy/_ui/css/chat_interface/column.css
  ragna/deploy/_ui/css/chat_interface/copybutton.css
  ragna/deploy/_ui/css/chat_interface/markdown.css
  ragna/deploy/_ui/css/chat_interface/textinput.css
  ragna/deploy/_ui/css/global/button.css
  ragna/deploy/_ui/css/global/divider.css
  ragna/deploy/_ui/css/global/select.css
  ragna/deploy/_ui/css/global/textinput.css
  ragna/deploy/_ui/css/left_sidebar/button.css
  ragna/deploy/_ui/css/left_sidebar/column.css
  ragna/deploy/_ui/css/left_sidebar/html.css
  ragna/deploy/_ui/css/main.css
  ragna/deploy/_ui/css/main_page/row.css
  ragna/deploy/_ui/css/modal_configuration/button.css
  ragna/deploy/_ui/css/modal_configuration/card.css
  ragna/deploy/_ui/css/modal_configuration/intslider.css
  ragna/deploy/_ui/css/modal_configuration/row.css
  ragna/deploy/_ui/css/modal_welcome/button.css
  ragna/deploy/_ui/css/right_sidebar/button.css
  ragna/deploy/_ui/css/right_sidebar/column.css
  ragna/deploy/_ui/css/right_sidebar/markdown.css
  ragna/deploy/_ui/css/source_accordion/accordion.css
  ragna/deploy/_ui/css/source_accordion/card.css
  ragna/deploy/_ui/css/source_accordion/html.css
  ragna/deploy/_ui/css/source_accordion/markdown.css
  ragna/deploy/_ui/left_sidebar.py
  ragna/deploy/_ui/main_page.py
  ragna/deploy/_ui/modal_configuration.py
  ragna/deploy/_ui/modal_welcome.py
  ragna/deploy/_ui/right_sidebar.py
  ragna/deploy/_ui/styles.py
  requirements-docker.lock
Labels: type: maintenance 🛠️, area: web-ui 💻

#368 [DOC] Add tutorial for adding your own objects
  docs/assets/images/ragna-tutorial-components.png
  docs/examples/gallery_streaming.py
  docs/references/config.md
  docs/tutorials/gallery_custom_components.py
  docs/tutorials/gallery_rest_api.py
  ragna/_docs.py
Labels: area: documentation 📖

#414 serve web UI with FastAPI / uvicorn
  .github/actions/setup-env/action.yml
  .github/workflows/test.yml
  environment-dev.yml
  pyproject.toml
  ragna/deploy/_api/core.py
  ragna/deploy/_ui/api_wrapper.py
  ragna/deploy/_ui/app.py
  ragna/deploy/_ui/auth_page.py
  ragna/deploy/_ui/central_view.py
  ragna/deploy/_ui/components/file_uploader.py
  ragna/deploy/_ui/css/auth/button.css
  ragna/deploy/_ui/css/auth/column.css
  ragna/deploy/_ui/css/auth/html.css
  ragna/deploy/_ui/css/auth/textinput.css
  ragna/deploy/_ui/js_utils.py
  ragna/deploy/_ui/logout_page.py
  ragna/deploy/_ui/modal_configuration.py
  ragna/deploy/_ui/resources/upload.js
  ragna/deploy/_ui/styles.py
  tests/deploy/api/utils.py
  tests/test_js_utils.py
Labels: area: web-ui 💻, area: rest-api 💻, dev: deploy

#419 Fix #415 : chat bubble
  ragna/deploy/_ui/css/left_sidebar/button.css
Labels: area: web-ui 💻

#425 refactor assistant streaming and create OpenAI compliant base class
  docs/examples/gallery_streaming.py
  docs/tutorials/gallery_python_api.py
  ragna/assistants/__init__.py
  ragna/assistants/_ai21labs.py
  ragna/assistants/_anthropic.py
  ragna/assistants/_api.py
  ragna/assistants/_cohere.py
  ragna/assistants/_google.py
  ragna/assistants/_http_api.py
  ragna/assistants/_llamafile.py
  ragna/assistants/_openai.py
  tests/assistants/test_api.py
Labels: area: developer-experience 🧑‍💻, dev: components

#426 add metadata filter
  ragna/core/__init__.py
  ragna/core/_metadata_filter.py
  tests/core/test_metadata_filter.py
Labels: dev: corpus
