Repository Quansight/ragna, pull requests merged in 2024-08, with the labels that each got.

#462 fix streaming handling for builtin assistants
  environment-dev.yml
  ragna/_utils.py
  ragna/assistants/_ai21labs.py
  ragna/assistants/_anthropic.py
  ragna/assistants/_cohere.py
  ragna/assistants/_google.py
  ragna/assistants/_http_api.py
  ragna/assistants/_ollama.py
  ragna/assistants/_openai.py
  tests/assistants/streaming_server.py
  tests/assistants/test_api.py
  tests/deploy/ui/test_ui.py
  tests/utils.py
Labels: area: python-api ⌨️

#476 support pydantic (de)serialization on MetadataFilter
  ragna/core/_metadata_filter.py
  tests/core/test_metadata_filter.py
Labels: dev: corpus

#478 fix lint and test for corpus dev branch
  ragna/deploy/_api/database.py
  ragna/source_storages/_chroma.py
  ragna/source_storages/_demo.py
  ragna/source_storages/_lancedb.py
  tests/core/test_e2e.py
  tests/deploy/api/test_e2e.py
  tests/source_storages/test_source_storages.py
Labels: dev: corpus

#479 support medata filter in the REST API
  ragna/core/_rag.py
  ragna/deploy/_api/core.py
  ragna/deploy/_api/database.py
  ragna/deploy/_api/orm.py
  ragna/deploy/_api/schemas.py
  ragna/deploy/_ui/api_wrapper.py
  scripts/add_chats.py
  tests/deploy/api/test_components.py
  tests/deploy/api/test_e2e.py
  tests/deploy/ui/test_ui.py
Labels: area: rest-api 💻, dev: corpus

#482 make Chat.prepare idempotent
  ragna/core/_rag.py
  tests/core/test_e2e.py
Labels: dev: corpus

#461 Use MetadataFilter in LanceDB
  ragna/source_storages/_lancedb.py
  tests/source_storages/test_source_storages.py
Labels: dev: corpus

#489 minor API fixes in preparation of the metadata filter UI
  ragna/deploy/_api/core.py
  ragna/deploy/_api/database.py
Labels: dev: corpus

#496 gracefully stop API when started by ragna ui
  ragna/deploy/_cli/core.py
  tests/deploy/ui/test_ui.py
Labels: type: bug 🐛, type: enhancement 💅, area: testing ✅

#497 handle zombie processes in docs
  ragna/_docs.py
Labels: type: bug 🐛, area: documentation 📖

#502 drop Python 3.9 and add support for 3.12
  .github/actions/setup-env/action.yml
  .github/workflows/test.yml
  .github/workflows/update-docker-requirements.yml
  Dockerfile
  environment-dev.yml
  pyproject.toml
  ragna/_compat.py
  ragna/assistants/_http_api.py
  ragna/core/_utils.py
  ragna/deploy/_api/core.py
  ragna/deploy/_api/orm.py
  ragna/deploy/_api/schemas.py
  ragna/deploy/_ui/api_wrapper.py
  ragna/deploy/_ui/central_view.py
  ragna/source_storages/_vector_database.py
  requirements-docker.lock
  tests/assistants/test_api.py
  tests/test_dependencies.py
Labels: type: maintenance 🛠️
