Repository Quansight/ragna, pull requests merged in 2024-07, with the labels that each got.

#436 refactor protocol model extraction to only check extra parameters
  ragna/core/_components.py
  ragna/core/_rag.py
  tests/core/test_rag.py
Labels: area: developer-experience 🧑‍💻, area: user-experience 🙋🏻‍♀️

#437 add release notes for v0.2.1
  docs/references/release-notes.md
Labels: area: documentation 📖, type: release 🏷️

#441 refactor document registering and upload
  ragna/core/__init__.py
  ragna/core/_document.py
  ragna/core/_rag.py
  ragna/deploy/_api.py
  ragna/deploy/_core.py
  ragna/deploy/_database.py
  ragna/deploy/_engine.py
  ragna/deploy/_schemas.py
  scripts/add_chats.py
  tests/deploy/api/test_batch_endpoints.py
  tests/deploy/api/test_components.py
  tests/deploy/api/test_e2e.py
Labels: dev: deploy

#444 update assistants in docker config
  ragna-docker.toml
Labels: type: maintenance 🛠️

#443 use backend engine in UI
  ragna/_cli/core.py
  ragna/deploy/_core.py
  ragna/deploy/_ui/api_wrapper.py
  ragna/deploy/_ui/app.py
  ragna/deploy/_ui/central_view.py
  ragna/deploy/_ui/left_sidebar.py
  ragna/deploy/_ui/modal_configuration.py
  tests/deploy/ui/test_ui.py
Labels: dev: deploy

#445 #391 Chat Ordering based upon the order of interaction
  ragna/deploy/_ui/left_sidebar.py
Labels: area: web-ui 💻

#456 Add metadata filter handling for builtin source storages
  docs/examples/gallery_streaming.py
  docs/tutorials/gallery_custom_components.py
  docs/tutorials/gallery_python_api.py
  ragna/assistants/_demo.py
  ragna/core/_components.py
  ragna/core/_rag.py
  ragna/deploy/_api/core.py
  ragna/source_storages/_chroma.py
  ragna/source_storages/_demo.py
  ragna/source_storages/_lancedb.py
  ragna/source_storages/_vector_database.py
  tests/core/test_e2e.py
  tests/core/test_rag.py
Labels: dev: corpus
